#!/bin/bash
# FORGE - QUICK REFERENCE & TROUBLESHOOTING GUIDE

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║        FORGE - SELF-HOSTED CLOUD DEV ENVIRONMENTS              ║"
echo "║              Quick Reference & Status Check                    ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Color codes
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "📋 SYSTEM STATUS"
echo "================"
echo ""

# Check services
echo "🔍 Checking containers..."
if docker compose -f cloud-dev/docker-compose.yml ps 2>/dev/null | grep -q "Up"; then
    echo -e "${GREEN}✅ All containers running${NC}"
else
    echo -e "${RED}❌ Some containers not running${NC}"
fi

echo ""
echo "📊 CONTAINER STATS"
echo "=================="
docker compose -f cloud-dev/docker-compose.yml stats --no-stream 2>/dev/null | tail -4

echo ""
echo "🌐 API ENDPOINTS"
echo "================"
echo "Backend:     http://localhost:4000"
echo "  - Health:   http://localhost:4000/health"
echo "  - Auth:     http://localhost:4000/api/auth/"
echo "  - Workspaces: http://localhost:4000/api/workspaces"
echo ""
echo "Orchestrator: http://localhost:5001"
echo "  - Health:   http://localhost:5001/health"
echo ""
echo "MongoDB:      mongodb://localhost:27017"
echo "  - Database: cloud-dev-env"
echo ""

echo "🔐 SECURITY FEATURES APPLIED"
echo "============================="
echo "  ✅ SSH Key Injection Prevention"
echo "  ✅ OAuth Security Hardening"
echo "  ✅ CORS Restricted to APP_URL"
echo "  ✅ Input Validation (Email, Password, URL)"
echo "  ✅ Stripe Webhook Deduplication"
echo "  ✅ Orchestrator Retry Logic"
echo "  ✅ Idle Reaper Error Handling"
echo "  ✅ WebSocket Keepalive"
echo "  ✅ Rate Limiting"
echo "  ✅ Comprehensive Logging"
echo ""

echo "📁 DOCUMENTATION"
echo "================"
echo "  📄 FINAL_REPORT.md         - Complete bug fix report"
echo "  📄 TEST_RESULTS.md         - API test results"
echo "  📄 BUG_FIXES_SUMMARY.md    - Detailed fix explanations"
echo "  📄 test-api.sh             - API test script"
echo ""

echo "🚀 COMMON COMMANDS"
echo "=================="
echo ""
echo "Start services:"
echo "  docker compose -f cloud-dev/docker-compose.yml up -d"
echo ""
echo "Stop services:"
echo "  docker compose -f cloud-dev/docker-compose.yml down"
echo ""
echo "View logs:"
echo "  docker compose -f cloud-dev/docker-compose.yml logs -f backend orchestrator"
echo ""
echo "Register orchestrator:"
echo "  export ORCHESTRATOR_TOKEN=\$(openssl rand -hex 32)"
echo "  docker compose -f cloud-dev/docker-compose.yml exec backend npm run register:host -- primary http://orchestrator:5001 \$ORCHESTRATOR_TOKEN"
echo ""
echo "Test API:"
echo "  curl http://localhost:4000/health"
echo "  curl http://localhost:5001/health"
echo ""

echo "⚙️  ENVIRONMENT VARIABLES"
echo "======================="
echo ""
echo "Required (set before docker-compose up):"
echo "  JWT_SECRET              - JWT signing secret (default: change_this_secret)"
echo "  ORCHESTRATOR_TOKEN      - Shared secret with orchestrator (default: change_this_secret)"
echo ""
echo "Optional (for features):"
echo "  SMTP_HOST, SMTP_PORT    - For email notifications"
echo "  STRIPE_SECRET_KEY       - For billing"
echo "  GOOGLE_CLIENT_ID/SECRET - For Google OAuth"
echo "  GITHUB_CLIENT_ID/SECRET - For GitHub OAuth"
echo "  NODE_ENV=production     - For secure cookies"
echo ""

echo "🐛 TROUBLESHOOTING"
echo "=================="
echo ""
echo "Backend not responding:"
echo "  docker compose -f cloud-dev/docker-compose.yml logs backend"
echo ""
echo "MongoDB not connecting:"
echo "  docker compose -f cloud-dev/docker-compose.yml logs mongo"
echo ""
echo "Orchestrator unreachable:"
echo "  docker compose -f cloud-dev/docker-compose.yml logs orchestrator"
echo ""
echo "Workspace creation failing:"
echo "  Check orchestrator logs for Docker errors"
echo "  Verify docker.sock is mounted in orchestrator"
echo ""
echo "Email not sending:"
echo "  Configure SMTP_* env vars"
echo "  Check SMTP credentials"
echo ""

echo "📚 BUG FIXES APPLIED"
echo "===================="
echo ""
echo "12 Critical Issues Fixed:"
echo "  1. SSH Key Injection Prevention"
echo "  2. OAuth State Cookie Cleanup"
echo "  3. OAuth Provider Timeout (10s)"
echo "  4. Email Validation (RFC 5322)"
echo "  5. Password Strength Enforcement"
echo "  6. Repo URL Validation"
echo "  7. Orchestrator Retry Logic"
echo "  8. ObjectId Validation"
echo "  9. Stripe Webhook Deduplication"
echo " 10. CORS Hardening"
echo " 11. WebSocket Keepalive (30s)"
echo " 12. Rate Limiting Protection"
echo ""

echo "💡 PRODUCTION CHECKLIST"
echo "======================="
echo ""
echo "Before deploying to production:"
echo "  [ ] Change JWT_SECRET (not 'change_this_secret')"
echo "  [ ] Change ORCHESTRATOR_TOKEN (not 'change_this_secret')"
echo "  [ ] Set NODE_ENV=production"
echo "  [ ] Configure SMTP_* for email"
echo "  [ ] Configure Stripe keys if using billing"
echo "  [ ] Set up HTTPS/TLS (put behind nginx/Caddy)"
echo "  [ ] Move webhook dedup to Redis (from in-memory)"
echo "  [ ] Enable structured logging"
echo "  [ ] Set up error monitoring (Sentry)"
echo "  [ ] Configure database backups"
echo ""

echo "═════════════════════════════════════════════════════════════════"
echo ""
